<a id='top'></a>
# Pandas Notes 1

* [Data Structures in Pandas](#datastruct)
* [DataFrame: Accessing Values,Adding and Deletion of Rows and Columns](#access)
* [Series Basic Functionality](#series)
* [DataFrame Basic Functionality](#dataframe)
* [Descriptive Statistics](#descriptive)
* [pipe(), apply() and applymap()](#pipe)

<a id='datastruct'></a>
### Data Structures in Pandas
[Back to top](#top)

In [1]:
import pandas as pd
import numpy as np

series1 = pd.Series(np.arange(3),index=list('abc'))
series2 = pd.Series({'a':0,'b':1,'c':2})
series3 = pd.Series(3,index=np.arange(3))

print('Series 1:\n',series1)
print('\nSeries 2:\n',series2)
print('\nSeries 3:\n',series3)

Series 1:
 a    0
b    1
c    2
dtype: int32

Series 2:
 a    0
b    1
c    2
dtype: int64

Series 3:
 0    3
1    3
2    3
dtype: int64

In [22]:
print('Accessing Values in Series')
print("\nseries1['a']: ",series1['a'])
print("\nseries2[['a','b']]:\n",series2[['a','b']])
print("\nseries3[1:3]:\n",series3[1:3])

Accessing Values in Series

series1['a']:  0

series2[['a','b']]:
 a    0
b    1
dtype: int64

series3[1:3]:
 1    3
2    3
dtype: int64

In [50]:
data1 = [['Alex',10],['Bob',12],['Clarke',13]]
df1 = pd.DataFrame(data1,columns=['Name','Age'])

data2 = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df2 = pd.DataFrame(data2)

print('DataFrame from Lists:\n',df1)
print('\nDataFrame from Dictionary:\n',df2)

DataFrame from Lists:
      Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

DataFrame from Dictionary:
     Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42

<a id='access'></a>
### DataFrame: Accessing Values,Adding and Deletion of Rows and Columns
[Back to top](#top)

In [51]:
print('Adding and Deleting Column')
print('\nSample DataFrame:\n',df2)

df2['Random'] = pd.Series(np.random.randint(1,11,4))
print('\nAdded new column "Random":\n',df2)

df2.pop('Random')
print('\nDeleting Random Column using pop function:\n',df2)

Adding and Deleting Column

Sample DataFrame:
     Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42

Added new column "Random":
     Name  Age  Random
0    Tom   28       2
1   Jack   34       8
2  Steve   29       6
3  Ricky   42       1

Deleting Random Column using pop function:
     Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42

In [53]:
df2['Random'] = pd.Series(np.random.randint(1,11,4))

print('Adding and Deleting Rows:')
print('\nSample Data:\n',df2)

row = pd.DataFrame({'Name':'Mark','Age':20,'Random':np.random.randint(1,11,1)})
df = df2.append(row,ignore_index=True)
print('\nAdding rows using append:\n',df)

row = pd.DataFrame({'Name':'Pat','Age':19,'Random':np.random.randint(1,11,1)})
df = pd.concat([df,row],ignore_index=True)
print('\nAdding rows using concat:\n',df)

df2 = df.drop([0,1])
print('\nDeleting 1st and 2nd Row:\n',df2)

Adding and Deleting Rows:

Sample Data:
     Name  Age  Random
0    Tom   28       1
1   Jack   34       1
2  Steve   29       1
3  Ricky   42       8

Adding rows using append:
     Name  Age  Random
0    Tom   28       1
1   Jack   34       1
2  Steve   29       1
3  Ricky   42       8
4   Mark   20       1

Adding rows using concat:
     Name  Age  Random
0    Tom   28       1
1   Jack   34       1
2  Steve   29       1
3  Ricky   42       8
4   Mark   20       1
5    Pat   19       9

Deleting 1st and 2nd Row:
     Name  Age  Random
2  Steve   29       1
3  Ricky   42       8
4   Mark   20       1
5    Pat   19       9

In [85]:
print('Column Selection - Period and Square Bracket can be used to access a column')
print('\nSample DataFrame\n',df)

print('\nName Column:\n',df.Name)
print('\nName and Random Column:\n',df[['Name','Random']])
print('\nColumn Selection using iloc and colon:\n',df.iloc[:,1:3])

Column Selection - Period and Square Bracket can be used to access a column

Sample DataFrame
     Name  Age  Random
0    Tom   28       1
1   Jack   34       1
2  Steve   29       1
3  Ricky   42       8
4   Mark   20       1
5    Pat   19       9

Name Column:
 0      Tom
1     Jack
2    Steve
3    Ricky
4     Mark
5      Pat
Name: Name, dtype: object

Name and Random Column:
     Name  Random
0    Tom       1
1   Jack       1
2  Steve       1
3  Ricky       8
4   Mark       1
5    Pat       9

Column Selection using iloc and colon:
    Age  Random
0   28       1
1   34       1
2   29       1
3   42       8
4   20       1
5   19       9

In [91]:
print('Row Selection')
print('\nSample DataFrame\n',df)

print('\nSelecting last row:\n',df.iloc[-1])

print('\nSelecting Name and Age in 2nd to 5th row:\n',df.iloc[1:5][['Name','Age']])

Row Selection

Sample DataFrame
     Name  Age  Random
0    Tom   28       1
1   Jack   34       1
2  Steve   29       1
3  Ricky   42       8
4   Mark   20       1
5    Pat   19       9

Selecting last row:
 Name      Pat
Age        19
Random      9
Name: 5, dtype: object

Selecting Name and Age in 2nd to 5th row:
     Name  Age
1   Jack   34
2  Steve   29
3  Ricky   42
4   Mark   20

<a id='series'></a>
### Series Basic Functionality
[Back to top](#top)

In [103]:
series = pd.Series(np.random.randint(1,101,20))

print('Series axes:',series.axes)
print('Is series empty?:',series.empty)
print('Series dimension:',series.ndim)
print('Series length:',series.size)
print('\nSeries values:',series.values)
print('\nTop 5 values using head():\n',series.head(5))
print('\nBottom 5 values using tail():\n',series.tail(5))

Series axes: [RangeIndex(start=0, stop=20, step=1)]
Is series empty?: False
Series dimension: 1
Series length: 20

Series values: [48 37 46 64 40 94 98 91 74 40 57 42 37 50 12 10 63 74  8  2]

Top 5 values using head():
 0    48
1    37
2    46
3    64
4    40
dtype: int32

Bottom 5 values using tail():
 15    10
16    63
17    74
18     8
19     2
dtype: int32

<a id='dataframe'></a>
### DataFrame Basic Functionality
[Back to top](#top)

In [2]:
data = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

dataframe = pd.DataFrame(data)

print('Sample DataFrame:\n',dataframe)
print('\nNumber of elements:\n',dataframe.size)

print('\nTop 3 rows:\n',dataframe.head(3))
print('\nBottom 3 rows:\n',dataframe.tail(3))

df = dataframe.set_index('Name')
print('\nSet Name column as index:\n',df)

Sample DataFrame:
     Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20
5  Smith   29    4.60
6   Jack   23    3.80

Number of elements:
 21

Top 3 rows:
     Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98

Bottom 3 rows:
     Name  Age  Rating
4  Steve   30     3.2
5  Smith   29     4.6
6   Jack   23     3.8

Set Name column as index:
        Age  Rating
Name
Tom     25    4.23
James   26    3.24
Ricky   25    3.98
Vin     23    2.56
Steve   30    3.20
Smith   29    4.60
Jack    23    3.80

<a id='descriptive'></a>
### Descriptive Statistics
[Back to top](#top)

count()	Number of non-null observations

sum()	Sum of values

mean()	Mean of Values

median()	Median of Values

mode()	Mode of values

std()	Standard Deviation of the Values

min()	Minimum Value

max()	Maximum Value

abs()	Absolute Value

prod()	Product of Values

cumsum()	Cumulative Sum

cumprod()	Cumulative Product

In [8]:
df = pd.read_csv('sampleData.csv')

df

,ProductID,Date,Zip,Units,Revenue,City,State,Region,District,Country,Manufacturer,IsCompete,Product,Category,Segment
0,580,1/2/2015,78758,1,834.4875,"Austin, TX, USA",TX,Central,District #23,USA,VanArsdel,N,Maximus UC-45,Urban,Convenience
1,559,1/2/2015,76209,1,629.9475,"Denton, TX, USA",TX,Central,District #22,USA,VanArsdel,N,Maximus UC-24,Urban,Convenience
2,596,1/2/2015,79763,1,766.2375,"Odessa, TX, USA",TX,Central,District #22,USA,VanArsdel,N,Maximus UC-61,Urban,Convenience
3,2064,1/2/2015,11758,1,577.4475,"Massapequa, NY, USA",NY,East,District #03,USA,Currus,N,Currus UE-24,Urban,Extreme
4,2055,1/2/2015,78610,1,656.1975,"Buda, TX, USA",TX,Central,District #23,USA,Currus,N,Currus UE-15,Urban,Extreme
5,2169,1/2/2015,10976,1,593.1975,"Sparkill, NY, USA",NY,East,District #03,USA,Victoria,N,Victoria UE-22,Urban,Extreme
6,599,1/4/2015,78245,1,886.9875,"San Antonio, TX, USA",TX,Central,District #23,USA,VanArsdel,N,Maximus UC-64,Urban,Convenience
7,596,1/4/2015,78521,1,766.2375,"Brownsville, TX, USA",TX,Central,District #23,USA,VanArsdel,N,Maximus UC-61,Urban,Convenience
8,604,1/4/2015,77320,1,524.9475,"Huntsville, TX, USA",TX,Central,District #23,USA,VanArsdel,N,Maximus UC-69,Urban,Convenience
9,559,1/4/2015,76133,1,629.9475,"Fort Worth, TX, USA",TX,Central,District #22,USA,VanArsdel,N,Maximus UC-24,Urban,Convenience
10,676,1/4/2015,76087,1,761.1975,"Weatherford, TX, USA",TX,Central,District #22,USA,VanArsdel,N,Maximus UC-41,Urban,Convenience
11,426,1/4/2015,75063,1,976.4475,"Irving, TX, USA",TX,Central,District #22,USA,VanArsdel,Y,Maximus UM-31,Urban,Moderation
12,491,1/4/2015,78539,1,892.4475,"Edinburg, TX, USA",TX,Central,District #23,USA,VanArsdel,Y,Maximus UM-96,Urban,Moderation
13,512,1/4/2015,78664,1,246.4875,"Round Rock, TX, USA",TX,Central,District #23,USA,VanArsdel,N,Maximus UR-01,Urban,Regular
14,1182,1/4/2015,78516,1,215.1975,"Alamo, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum UE-18,Urban,Extreme
15,1182,1/4/2015,77082,1,209.9475,"Houston, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum UE-18,Urban,Extreme
16,1053,1/4/2015,12946,1,293.9475,"Lake Placid, NY, USA",NY,East,District #01,USA,Pirum,N,Pirum MA-11,Mix,All Season
17,1053,1/4/2015,77962,1,293.9475,"Ganado, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum MA-11,Mix,All Season
18,1120,1/4/2015,14505,1,183.6975,"Marion, NY, USA",NY,East,District #06,USA,Pirum,N,Pirum RS-08,Rural,Select
19,676,1/5/2015,75020,1,761.1975,"Denison, TX, USA",TX,Central,District #22,USA,VanArsdel,N,Maximus UC-41,Urban,Convenience
20,400,1/5/2015,77318,1,892.4475,"Willis, TX, USA",TX,Central,District #23,USA,VanArsdel,Y,Maximus UM-05,Urban,Moderation
21,491,1/5/2015,75662,1,892.4475,"Kilgore, TX, USA",TX,Central,District #24,USA,VanArsdel,Y,Maximus UM-96,Urban,Moderation
22,1182,1/5/2015,77043,1,215.1975,"Houston, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum UE-18,Urban,Extreme
23,1182,1/5/2015,77449,1,225.6975,"Katy, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum UE-18,Urban,Extreme
24,2045,1/5/2015,78258,1,514.4475,"San Antonio, TX, USA",TX,Central,District #23,USA,Currus,N,Currus UE-05,Urban,Extreme
25,2254,1/5/2015,13152,1,60.3225,"Skaneateles, NY, USA",NY,East,District #01,USA,Aliqui,N,Aliqui RP-51,Rural,Productivity
26,2255,1/5/2015,13152,1,60.3225,"Skaneateles, NY, USA",NY,East,District #01,USA,Aliqui,N,Aliqui RP-52,Rural,Productivity
27,1053,1/5/2015,78543,1,293.9475,"Elsa, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum MA-11,Mix,All Season
28,2091,1/5/2015,13905,2,367.3950,"Binghamton, NY, USA",NY,East,District #01,USA,Currus,N,Currus UC-26,Urban,Convenience
29,580,1/6/2015,76544,1,834.4875,"Fort Hood, TX, USA",TX,Central,District #23,USA,VanArsdel,N,Maximus UC-45,Urban,Convenience
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5488,1182,6/30/2015,77303,1,215.1975,"Conroe, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5489,1182,6/30/2015,75551,1,209.9475,"Atlanta, TX, USA",TX,Central,District #25,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5490,1182,6/30/2015,76013,1,209.9475,"Arlington, TX, USA",TX,Central,District #22,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5491,1182,6/30/2015,76137,1,236.1975,"Fort Worth, TX, USA",TX,Central,District #22,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5492,1182,6/30/2015,76209,1,236.1975,"Denton, TX, USA",TX,Central,District #22,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5493,1182,6/30/2015,10306,1,236.1975,"Staten Island, NY, USA",NY,East,District #03,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5494,1182,6/30/2015,10941,1,236.1975,"Middletown, NY, USA",NY,East,District #01,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5495,1182,6/30/2015,11201,1,225.6975,"Brooklyn, NY, USA",NY,East,District #03,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5496,1182,6/30/2015,10605,1,225.6975,"White Plains, NY, USA",NY,East,District #03,USA,Pirum,N,Pirum UE-18,Urban,Extreme
5497,2045,6/30/2015,10462,1,514.4475,"Bronx, NY, USA",NY,East,District #03,USA,Currus,N,Currus UE-05,Urban,Extreme
5498,2045,6/30/2015,14445,1,514.4475,"East Rochester, NY, USA",NY,East,District #06,USA,Currus,N,Currus UE-05,Urban,Extreme
5499,2045,6/30/2015,76086,1,514.4475,"Weatherford, TX, USA",TX,Central,District #22,USA,Currus,N,Currus UE-05,Urban,Extreme
5500,2045,6/30/2015,76259,1,514.4475,"Ponder, TX, USA",TX,Central,District #22,USA,Currus,N,Currus UE-05,Urban,Extreme
5501,702,6/30/2015,10033,1,314.9475,"New York, NY, USA",NY,East,District #03,USA,Natura,N,Natura MA-09,Mix,All Season
5502,702,6/30/2015,11434,1,312.3225,"Jamaica, NY, USA",NY,East,District #03,USA,Natura,N,Natura MA-09,Mix,All Season
5503,1916,6/30/2015,76458,1,299.1975,"Jacksboro, TX, USA",TX,Central,District #22,USA,Currus,N,Currus MA-09,Mix,All Season
5504,1920,6/30/2015,76958,1,278.1975,"Water Valley, TX, USA",TX,Central,District #22,USA,Currus,N,Currus MA-13,Mix,All Season
5505,1053,6/30/2015,10307,1,314.9475,"Staten Island, NY, USA",NY,East,District #03,USA,Pirum,N,Pirum MA-11,Mix,All Season
5506,1053,6/30/2015,11203,1,314.9475,"Brooklyn, NY, USA",NY,East,District #03,USA,Pirum,N,Pirum MA-11,Mix,All Season
5507,1053,6/30/2015,12801,1,314.9475,"Glens Falls, NY, USA",NY,East,District #01,USA,Pirum,N,Pirum MA-11,Mix,All Season
5508,1053,6/30/2015,14813,1,314.9475,"Belmont, NY, USA",NY,East,District #06,USA,Pirum,N,Pirum MA-11,Mix,All Season
5509,1053,6/30/2015,78063,1,293.9475,"Pipe Creek, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum MA-11,Mix,All Season
5510,1053,6/30/2015,77802,1,293.9475,"Bryan, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum MA-11,Mix,All Season
5511,1053,6/30/2015,77845,1,293.9475,"College Station, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum MA-11,Mix,All Season
5512,1053,6/30/2015,78613,1,293.9475,"Cedar Park, TX, USA",TX,Central,District #23,USA,Pirum,N,Pirum MA-11,Mix,All Season
5513,1053,6/30/2015,79831,1,293.9475,"Alpine, TX, USA",TX,Central,District #22,USA,Pirum,N,Pirum MA-11,Mix,All Season
5514,2284,6/30/2015,14086,1,330.6975,"Lancaster, NY, USA",NY,East,District #06,USA,Aliqui,N,Aliqui RS-17,Rural,Select
5515,2284,6/30/2015,14094,1,330.6975,"Lockport, NY, USA",NY,East,District #06,USA,Aliqui,N,Aliqui RS-17,Rural,Select
5516,2277,6/30/2015,14304,1,293.9475,"Niagara Falls, NY, USA",NY,East,District #06,USA,Aliqui,N,Aliqui RS-10,Rural,Select
5517,993,6/30/2015,76051,2,766.3950,"Grapevine, TX, USA",TX,Central,District #22,USA,Natura,N,Natura UC-56,Urban,Convenience

In [35]:
print('Total Revenue of VanArsdel:',round(df[df.Manufacturer=='VanArsdel'].Revenue.sum(),2))
print('Total count of revenue greater than 1000:',df.Revenue[df['Revenue']>1000].count()-1)
print('Average revenue in Rural:',round(df[df.Category=='Rural'].Revenue.mean(),2))
print('Maximum Revenue:',round(df.Revenue.max(),2))
print('Minimum Revenue:',round(df.Revenue.min(),2))

Total Revenue of VanArsdel: 1708741.49
Total count of revenue greater than 1000: 64
Average revenue in Rural: 197.12
Maximum Revenue: 7336.46
Minimum Revenue: 56.65

In [37]:
print(df.describe().Revenue)

count    5518.000000
mean      548.206275
std       313.755539
min        56.647500
25%       288.697500
50%       524.947500
75%       834.487500
max      7336.455000
Name: Revenue, dtype: float64

<a id='pipe'></a>
### pipe(), apply() and applymap()
[Back to top](#top)

In [47]:
df = pd.DataFrame(np.random.randint(1,101,(7,3)),columns=['Random1','Random2','Random3'])

print('Sample DataFrame:\n',df)

print('\npipe() takes the whole dataframe as argument: df.pipe(lambda x: print(x))\n')
df.pipe(lambda x: print(x))

print('\nprint(df.pipe(lambda x: x*2)\n')
print(df.pipe(lambda x: x*2))

Sample DataFrame:
    Random1  Random2  Random3
0       56       34       96
1       61       89       70
2       23       69       20
3       67       60       13
4       42       29       10
5       30       98       38
6       85       86      100

pipe() takes the whole dataframe as argument: df.pipe(lambda x: print(x))

   Random1  Random2  Random3
0       56       34       96
1       61       89       70
2       23       69       20
3       67       60       13
4       42       29       10
5       30       98       38
6       85       86      100

print(df.pipe(lambda x: x*2)

   Random1  Random2  Random3
0      112       68      192
1      122      178      140
2       46      138       40
3      134      120       26
4       84       58       20
5       60      196       76
6      170      172      200

In [67]:
print('Sample DataFrame:\n',df)

print('\napply() takes each column(default axis=0) as argument: df.apply(lambda x: print(x))\n')
df.apply(lambda x: print(x))

print('\nprint(df.apply(lambda x: x*2 if x.name == \'Random2\' else x))\n')
print(df.apply(lambda x: x*2 if x.name == 'Random2' else x))

print('\nprint(df.apply(lambda x: x*3 if x.name == 0 else x,axis=1))\n')
print(df.apply(lambda x: x*3 if x.name == 0 else x,axis=1))

Sample DataFrame:
    Random1  Random2  Random3
0       56       34       96
1       61       89       70
2       23       69       20
3       67       60       13
4       42       29       10
5       30       98       38
6       85       86      100

apply() takes each column(default axis=0) as argument: df.apply(lambda x: print(x))

0    56
1    61
2    23
3    67
4    42
5    30
6    85
Name: Random1, dtype: int32
0    34
1    89
2    69
3    60
4    29
5    98
6    86
Name: Random2, dtype: int32
0     96
1     70
2     20
3     13
4     10
5     38
6    100
Name: Random3, dtype: int32

print(df.apply(lambda x: x*2 if x.name == 'Random2' else x))

   Random1  Random2  Random3
0       56       68       96
1       61      178       70
2       23      138       20
3       67      120       13
4       42       58       10
5       30      196       38
6       85      172      100

print(df.apply(lambda x: x*3 if x.name == 0 else x,axis=1))

   Random1  Random2  Random3
0      168      102      288
1       61       89       70
2       23       69       20
3       67       60       13
4       42       29       10
5       30       98       38
6       85       86      100

In [68]:
print('Sample DataFrame:\n',df)

print('\napplymap() takes each values as argument: df.applymap(lambda x: \'pandas\' if x>50 else x)\n')
print(df.applymap(lambda x: 'pandas' if x>50 else x))

Sample DataFrame:
    Random1  Random2  Random3
0       56       34       96
1       61       89       70
2       23       69       20
3       67       60       13
4       42       29       10
5       30       98       38
6       85       86      100

applymap() takes each values as argument: df.applymap(lambda x: 'pandas' if x>50 else x)

  Random1 Random2 Random3
0  pandas      34  pandas
1  pandas  pandas  pandas
2      23  pandas      20
3  pandas  pandas      13
4      42      29      10
5      30  pandas      38
6  pandas  pandas  pandas